# Generated by Django 4.1.7 on 2023-05-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0002_car_base_price_car_daily_rate_car_doors_car_has_ac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.TextField(choices=[('ручная', 'ручная'), ('автоматическая', 'автоматическая')]),
        ),
    ]
