# Generated by Django 4.1.7 on 2023-05-05 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0003_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.RegexValidator(message='Invalid date format. DD.MM.YYYY is required.', regex='^\\d{2}\\.\\d{2}\\.\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.RegexValidator(message='Invalid date format. DD.MM.YYYY is required.', regex='^\\d{2}\\.\\d{2}\\.\\d{4}$')]),
        ),
    ]
