# Generated by Django 4.1.7 on 2023-05-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0007_alter_rentalagreement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='start_date',
            field=models.DateField(),
        ),
    ]
